# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '18.0'
target 'dday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dday
  pod 'MCEmojiPicker', :git => 'https://github.com/izyumkin/MCEmojiPicker.git'
end

target 'iosOnlyShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosOnlyShare

end

target 'iosWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosWidgetExtension

end
